services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    hostname: adguard
    networks:
      - applications
    labels:
      - "logaggregation=yes"
      - "traefik.enable=true"
      - "traefik.http.routers.adguard-main.rule=Host(`adguard.${HOST}`)"
      - "traefik.http.routers.adguard-main.service=main-service"
      - "traefik.http.services.main-service.loadbalancer.server.port=3000"
      - "traefik.docker.network=applications"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - adguard_config:/opt/adguardhome/conf
      - ${CONFIG_PATH:-.}/config/AdGuardHome.yaml:/opt/adguardhome/conf/AdGuardHome.yaml
      - adguard_work:/opt/adguardhome/work
    restart: unless-stopped
    #healthcheck:
    #  test: "/bin/netstat -pant | /bin/grep 53"
    #  interval: 45s
    #  timeout: 30s
    #  retries: 3

networks:
  applications:
    external: true

volumes:
  adguard_config:
    name: adguard_config
  adguard_work:
    name: adguard_work
